# docker-compose.yaml (or default.yaml)
# This file includes all the individual service definitions.
# Requires Docker Compose version 3.8 or later for the 'include' directive.
include:
  # Include common configurations
  - ./common/networks.yaml
  - ./common/volumes.yaml

  # Include individual service definitions
  - ./services/traefik.yaml
  - ./services/glance.yaml
  - ./services/qbittorrent.yaml
  - ./services/resilio-sync.yaml
  - ./services/portainer.yaml
  - ./services/prowlarr.yaml
  - ./services/jackett.yaml
  - ./services/jellyfin.yaml
  - ./services/sonarr.yaml
  - ./services/filebrowser.yaml
  - ./services/watchtower.yaml
  - ./services/radarr.yaml
  - ./services/bazarr.yaml
  - ./services/jellyseerr.yaml
  - ./services/duplicati.yaml
  - ./services/flaresolverr.yaml # Include flaresolverr before suwayomi if dependency order matters for readability
  - ./services/suwayomi.yaml
  - ./services/free-games-claimer.yaml
  - ./services/syncify.yaml

# You can optionally define networks/volumes directly here instead of common/ files,
# or add global configurations if needed, but keeping them separate is cleaner.

# Example: Defining networks/volumes here instead of including:
# networks:
#   proxy_network:
#     driver: bridge
#
# volumes:
#   portainer_data:
#     external: true