include:
  # Include common configurations
  - ./common/networks.yaml
  - ./common/volumes.yaml

  # Include reverse proxy service
  - ./services/traefik.yaml

  # Include media management services
  - ./services/sonarr.yaml
  - ./services/radarr.yaml
  - ./services/bazarr.yaml
  - ./services/jellyfin.yaml
  - ./services/jellyseerr.yaml
  - ./services/syncify.yaml

  # Include download and synchronization services
  - ./services/qbittorrent.yaml
  - ./services/resilio-sync.yaml

  # Include monitoring and management services
  - ./services/portainer.yaml
  - ./services/watchtower.yaml
  - ./services/glance.yaml

  # Include indexer services
  - ./services/prowlarr.yaml
  - ./services/jackett.yaml

  # Include backup and file management services
  - ./services/filebrowser.yaml
  - ./services/duplicati.yaml

  # Include miscellaneous services
  - ./services/flaresolverr.yaml 
  - ./services/suwayomi.yaml
  - ./services/free-games-claimer.yaml
