include:
  # Include common configurations
  - ./common/networks.yaml
  - ./common/volumes.yaml

  # Include individual service definitions
  - ./services/traefik.yaml
  - ./services/glance.yaml
  - ./services/qbittorrent.yaml
  - ./services/resilio-sync.yaml
  - ./services/portainer.yaml
  - ./services/prowlarr.yaml
  - ./services/jackett.yaml
  - ./services/jellyfin.yaml
  - ./services/sonarr.yaml
  - ./services/filebrowser.yaml
  - ./services/watchtower.yaml
  - ./services/radarr.yaml
  - ./services/bazarr.yaml
  - ./services/jellyseerr.yaml
  - ./services/duplicati.yaml
  - ./services/flaresolverr.yaml 
  - ./services/suwayomi.yaml
  - ./services/free-games-claimer.yaml
  - ./services/syncify.yaml
