services:
  free-games-claimer:
    image: ghcr.io/vogler/free-games-claimer:${FREE_GAMES_CLAIMER_VERSION}
    container_name: free-games-claimer
    command: bash -c "node epic-games; node gog; echo sleeping; sleep 1d"
    environment:
      - NOTIFY=${FREE_GAMES_NOTIFY_URL} 
      - NOTIFY_TITLE=My Free Games Claimer
      - GOG_EMAIL=${GOG_EMAIL}
      - GOG_PASSWORD=${GOG_PASSWORD}
    labels:
      - "glance.name=Free Games Claimer"
      - "glance.icon=https://raw.githubusercontent.com/game-icons/icons/846f3e9699d4199e35aeb9b454b4d07809c3441a/delapouite/gamepad.svg"
      - "glance.url=http://game.${BASE_DOMAIN}/"
      - "glance.description=Free Games Claimer"
      - "traefik.enable=true"
      - "traefik.http.routers.game.middlewares=authentik@docker" 
      - "traefik.http.routers.game.rule=Host(`game.${BASE_DOMAIN}`)"
      - "traefik.http.routers.game.entrypoints=web"
      - "traefik.http.services.game.loadbalancer.server.port=6080"
    volumes:
      - ${DOCKER_CONFIG_BASE}/Free_Game_Claim_Config:/fgc/data
    networks:
      - proxy_network
    restart: unless-stopped