services:
    gitea:
        image: gitea/gitea:latest
        container_name: gitea-server
        logging:
            driver: loki:latest
            options:
                loki-url: ${LOKI_URL}
                loki-retries: 5
                loki-max-backoff: 1800ms
                loki-timeout: 1s
                keep-file: "true"
                mode: "non-blocking"
        # environment:
        #     - USER_UID=${PUID}
        #     - USER_GID=${PGID}
        volumes:
            - ${DOCKER_CONFIG_BASE}/Gitea_Config/data:/var/lib/gitea
            - ${DOCKER_CONFIG_BASE}/Gitea_Config/config:/etc/gitea
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - proxy_network
        ports:
            - "3000:3000"
            - "2221:22"
        restart: unless-stopped
