services:
    runner:
        image: docker.io/gitea/act_runner:nightly
        environment:
            #CONFIG_FILE: ./config.yaml
            GITEA_INSTANCE_URL: "${INSTANCE_URL}"
            GITEA_RUNNER_REGISTRATION_TOKEN: "${REGISTRATION_TOKEN}"
            GITEA_RUNNER_NAME: "${RUNNER_NAME}"
            GITEA_RUNNER_LABELS: "${RUNNER_LABELS}"
        ports:
            - "8088:8088"
        volumes:
            #- ./config.yaml:/config.yaml
            - ${DOCKER_CONFIG_BASE}/Gitea_Runner_Config/data:/data
            - /var/run/docker.sock:/var/run/docker.sock
