services:
    runner:
        image: docker.io/gitea/act_runner:nightly
        container_name: gitea-runner
        logging:
            driver: loki:latest
            options:
                loki-url: ${LOKI_URL}
                loki-retries: 5
                loki-max-backoff: 1800ms
                loki-timeout: 1s
                keep-file: "true"
                mode: "non-blocking"
        environment:
            #CONFIG_FILE: ./config.yaml
            GITEA_INSTANCE_URL: "${INSTANCE_URL}"
            GITEA_RUNNER_REGISTRATION_TOKEN: "${REGISTRATION_TOKEN}"
            GITEA_RUNNER_NAME: "${RUNNER_NAME}"
            GITEA_RUNNER_LABELS: "${RUNNER_LABELS}"
        ports:
            - "8088:8088"
        labels:
            - "glance.parent=gitea"
            - "glance.name=runner"
        volumes:
            #- ./config.yaml:/config.yaml
            - ${DOCKER_CONFIG_BASE}/Gitea_Runner_Config/data:/data
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped
