services:
    jackett:
        image: lscr.io/linuxserver/jackett:${JACKETT_VERSION}
        container_name: jackett
        logging:
            driver: loki:latest
            options:
                loki-url: ${LOKI_URL}
                loki-retries: 5
                loki-max-backoff: 1800ms
                loki-timeout: 1s
                keep-file: "true"
                mode: "non-blocking"
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - AUTO_UPDATE=true
            - TZ=${TZ}
        ports:
            - "9117:9117"
        labels:
            - "glance.name=Jackett"
            - "glance.icon=sh:jackett"
            - "glance.url=http://jackett.${BASE_DOMAIN}/"
            - "glance.description=Indexer Manager"
            # - "traefik.enable=true"
            # - "traefik.http.routers.jackett.rule=Host(`jackett.${BASE_DOMAIN}`)"
            # - "traefik.http.routers.jackett.entrypoints=web"
            # - "traefik.http.services.jackett.loadbalancer.server.port=9117"
        networks:
            - proxy_network
        volumes:
            - ${DOCKER_CONFIG_BASE}/Jackett_Config:/config
            - ${MEDIA_DOWNLOADS_PATH}:/downloads
        restart: unless-stopped
