services:
    node-exporter:
        image: prom/node-exporter:latest
        container_name: nodeexporter
        restart: unless-stopped
        command: " --path.rootfs=/host "
        logging:
            driver: loki:latest
            options:
                loki-url: ${LOKI_URL}
                loki-retries: 5
                loki-max-backoff: 1800ms
                loki-timeout: 1s
                keep-file: "true"
                mode: "non-blocking"
        pid: host
        volumes:
            - /:/host:ro,rslave
        networks:
            - proxy_network
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nodeexporter.rule=Host(`nodeexporter.${BASE_DOMAIN}`)"
            - "traefik.http.routers.nodeexporter.entrypoints=web"
            - "traefik.http.services.nodeexporter.loadbalancer.server.port=9100"
            - "glance.parent=grafana"
            - "glance.name=nodeexporter"
