services:
    prometheus:
        image: docker.io/prom/prometheus:latest
        container_name: prometheus
        # ports:
        #     - 9090:9090
        command: "--config.file=/etc/prometheus/prometheus.yml"
        volumes:
            - ../common/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - prometheus-data:/prometheus
        networks:
            - proxy_network
        labels:
            - "glance.parent=grafana"
            - "glance.name=prometheus"
        restart: unless-stopped
