services:
    wallsite:
        image: ghcr.io/rishabh5321/wallsite:latest
        container_name: wallsite
        ports:
            - "8000:8000"
        networks:
            - proxy_network
        labels:
            - "glance.name=wallsite"
            - "glance.icon=https://raw.githubusercontent.com/Rishabh5321/wallsite/refs/heads/main/src/assets/favicon.png"
            - "glance.url=https://wallsite.${BASE_DOMAIN}/"
            - "glance.description=Wallpapers"
        volumes:
            - ${WALLSITE_SRC}:/app/wallpapers
        restart: unless-stopped
